df <- read.csv("titanic_project.csv", header=TRUE)
head(df)
#Remove the first column
df <- subset(df, select = -c(X))
head(df)
df$survived <- factor(df$survived)
df$pclass <- factor(df$pclass)
df$survived <- factor(df$survived)
df$sex <- factor(df$sex)
#set.seed(1234)
#i <- sample(1:nrow(df), 0.75*nrow(df), replace=FALSE)
train <- df[1:900, ]
test <- df[901:nrow(df), ]
# head(train)
# head(test)
# tail(train)
tail(test)
system.time(glm1 <- glm(survived~., data=train, family="binomial"))
summary(glm1)
probs <- predict(glm1, newdata=test, type="response")
pred <- ifelse(probs>0.5, 1, 0)
acc_lr <- mean(pred==test$survived)
print(paste("accuracy Logistic regression= ", acc_lr))
table(pred, test$survived)
true_positives <- sum(ifelse(pred==1 & test$survived==1, 1.0, 0.0))
false_positives <- sum(ifelse(pred==1 & test$survived==0, 1.0, 0.0))
true_negatives <- sum(ifelse(pred==0 & test$survived==0, 1.0, 0.0))
false_negatives <- sum(ifelse(pred==0 & test$survived==1, 1.0, 0.0))
sensitivity <- true_positives/(true_positives+false_negatives)
specificity <- true_negatives/(true_negatives+false_positives)
print(paste("Sensitivity Logistic regression= ", sensitivity))
print(paste("Specificity Logistic regression== ", specificity))

